name: Rodar testes simples

on:
  push:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Mostrar mensagem
        run: echo "GitHub Actions funcionando!"
